language: go
go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
matrix:
  allow_failures:
  - go: 1.9 
script:
  - make setup
  - make
  - make test
  - make cover
after_success:
  - bash <(curl -s https://codecov.io/bash) -f .GOPATH/cover/all.merged
